export const titles = [
    'Apocalypto',
    'I Theia Apo to Chicago',
    'O anthropos pou gyrise apo ti zesti',
    'Apo pou pane gia ti havouza',
    'O dimos apo ta Trikala',
    'The Love Song of M. Anderson Vincent',
    'O anthropos pou gyrise apo ta piata!',
    'Gefsi apo... Ellada!',
    'Granita apo melani',
    'Diestrammenoi apo tin genna tous',
    'O Kotsos exo apo to N.A.T.O.',
    'O anthropos apo to "Chernobyl"',
    'The World According to Ion B.',
    'B-Movie: The Shooting of "Farmhouse Massacre"',
    'A Day in the Death of Donny B.',
    'The Nina B. Affair',
    'The Cruise of the Jasper B',
    'Brown Bag Diaries: Ridin the Blinds in B Minor',
    'Brace for Impact: The Chesley B. Sullenberger Story',
    'Attack of the Killer B-Movies',
    'K-On! The Movie',
    'K-20: The Fiend with Twenty Faces',
    'Detective K: Secret of the Lost Island',
    'The Gospel According to Philip K. Dick',
    'Detective K: Secret of the Living Dead',
    'The Great K & A Train Robbery',
    'Kenny Powers: The K-Swiss MFCEO',
    'Azorian: The Raising of the K-129',
    'K-19: The Widowmaker',
    'Ma Vie en Rose',
    'Chow lok yuen',
    'Black',
    'The Kids Are All Right',
    'Bin lim mai ching',
    'Hated: GG Allin & the Murder Junkies',
    'Godard Mon Amour',
    'Épouse-moi mon pote',
    'Ana, mon amour',
    'Chuye Dile Mon',
    'Mon Mon Mon Monsters',
    'Echo Jew Gong Lok',
    'Dan sun bo lok',
    'Awasarn Lok Suay',
    'Sub khu ku lok',
    'Sex Drive',
    'Learning to Drive',
    'Mulholland Drive',
    'The Exorcism of Emily Rose',
    'Now You See Me',
    'See No Evil',
    'All I See Is You'
];
