export const titles = [
    'A Sea Cave Near Lisbon',
    'A Woman\'s Way',
    'Aladdin and the Wonderful Lamp',
    'Alice in Wonderland',
    'All I See Is You',
    'Ana mon amour',
    'Apocalypto',
    'Aquaman',
    'Awasarn Lok Suay',
    'Annihilation',
    'Azorian: The Raising of the K-129',
    'B-Movie: The Shooting of "Farmhouse Massacre"',
    'Ballet libella',
    'Ben Hur',
    'Bin lim mai ching',
    'Bird Box',
    'Black Mirror: Bandersnatch',
    'Black',
    'Brace for Impact: The Chesley B. Sullenberger Story',
    'Brown Bag Diaries: Ridin the Blinds in B Minor',
    'Bumblebee',
    'Casey at the Bat',
    'Chow lok yuen',
    'Chuye Dile Mon',
    'Cinderella',
    'Captain Marvel',
    'Criminal Minds',
    'Danse fleur de lotus',
    'Doctor Who',
    'Detective K: Secret of the Living Dead',
    'Echo Jew Gong Lok',
    'Ella Lola, a la Trilby',
    'Escape Room',
    'Gefsi apo... Ellada!',
    'Glass',
    'Godard Mon Amour',
    'Grandma\'s Reading Glass',
    'Green Book',
    'Hamlet',
    'Hellboy',
    'Halloween',
    'Hereditary',
    'Hated: GG Allin & the Murder Junkies',
    'How to Train Your Dragon: The Hidden World',
    'I Theia Apo to Chicago',
    'K-19: The Widowmaker',
    'K-20: The Fiend with Twenty Faces',
    'K-On! The Movie',
    'L\'aveugle',
    'Learning to Drive',
    'No Escape Room',
    'Ma Vie en Rose',
    'Macbeth',
    'Mon Mon Mon Monsters',
    'Mulholland Drive',
    'Now You See Me',
    'Mary Queen of Scots',
    'Mowgli',
    'Mission: Impossible - Fallout',
    'O anthropos pou gyrise apo ta piata!',
    'O anthropos pou gyrise apo ti zesti',
    'Robbery Under Arms',
    'Roma',
    'Secreto de confesión',
    'See No Evil',
    'Sex Drive',
    'Split',
    'Playdate',
    'Stan & Ollie',
    'The Call of the Wild',
    'The Enchanted Drawing',
    'The Exorcism of Emily Rose',
    'The Favourite',
    'The Gospel According to Philip K. Dick',
    'The Great K & A Train Robbery',
    'The House That Jack Built',
    'The Kids Are All Right',
    'The Legacy',
    'Twisted',
    'Web of Lies',
    'The Merchant of Venice',
    'The Mule',
    'The Pioneers',
    'The Reckoning',
    'The Snowman',
    'Truth or Dare',
    'The World According to Ion B.',
    'Titans',
    'Transformations',
    'Uncle Tom\'s Cabin',
    'Upside',
    'Venom',
    'Vice',
    'Výstavní párkar a lepic plakátù',
    'You',
];
